#
# Calendar Configuration file
#
# see https://github.com/niccokunzmann/open-web-calendar/blob/master/default_specification.yml
#

title: "Amman Valley MakerSpace - Events, Dates and Meetings"

url:
# calendar for the forum
- https://ammanvalley.foss.wales/calendar.ics
# calendar for the volunteers
- https://calendar.google.com/calendar/ical/2f7e4052428e2c8edfe842675f5141d958787c50743c184c41613dac9ed7a9e6%40group.calendar.google.com/public/basic.ics

tabs:
- month
- week
- day
- agenda


